version: '3.9'

services:
  nats:
    image: nats

  backend:
    build: ./backend
    scale: 2
    depends_on:
      - nats

  nginx:
    build: ./nginx
    depends_on:
      - backend
    ports:
      - "80:80" 
